### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by dkolepp** [someth2say/xmlformat#2]
I was unable to "try" this hook; I got permissions issues related to the container trying to modify local files:

![image](https://user-images.githubusercontent.com/10145457/70925451-3da89e80-1ff9-11ea-88f9-2d9ea9359725.png)

**Comment by dkolepp** [comment]
Note: I am using podman, with the podman-alias running.  My container does not have "privilege" permissions...

**Comment by someth2say** [comment]
Mmm... interesting.
I had this same issue with Docker, but I finally solved it by adding "require_serial: true" to the hook definition file.
Can you share the your "pre-commit-hooks.yml" file in your local repo?

Also, not sure how "podman-alias" works (I guess it is just an alias docker=sudo podman, isn't it?).
What version of Podman are you using?

**Comment by dkolepp** [comment]
I am using a subscribed RHEL 7.7 host, with the following:
```
[dank@rhel-laptop DO280 (dkolepp/pcommit-config)]$ podman version
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.3
OS/Arch:            linux/amd64
```
and also have the `podman-docker` package installed.

## .pre-commit-hooks.yaml
```
- id: xmlformat
  name: XML Formatter
  description: >
    Formats XML files according GLS formating rules
  entry: quay.io/someth2say/xmlformat:0.1
  types: [xml]
  language: docker_image
  require_serial: true
```

**Comment by dkolepp** [comment]
This is the content of my: `/usr/bin/docker`:

```
#!/bin/sh
[ -f /etc/containers/nodocker ] || \
echo "Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg." >&2
exec /usr/bin/podman "$@"
```

**Comment by someth2say** [comment]
Given the issues found with podman with rootless containers, and as a temporary solution, I am removing support podman.
My recommendation: use the perl or ruby versions of the script.
