### ISSUE TITLE
Consider /etc for config file

### ISSUE THREAD

**Issue by tomschr** [someth2say/xmlformat#6]
# Situation

As far as I can see, the configuration file `xmlformat.conf` is detected in two ways:

* use the current directory where `xmlformat.pl` or `xmlformat.rb` is run
* use the environment variable `XMLFORMAT_CONF`

Problem: when the scripts are installed at `/usr/bin`, the config file would need to stay here too. However, this is discouraged from FHS which searches config files at `/etc`.

# Proposed solution

Both scripts should additionally search the config files at:

* `/etc/xmlformat.conf`
* search for the environment variable defined in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

Maybe it would make sense to order these options:

1. Investigate the environment variable `XMLFORMAT_CONF`.
2. Investigate the environment variable `XDG_CONFIG_DIRS`.
2. Search in the current directory where the base script is run.
2. Search in `/etc/xmlformat.conf`.

**Comment by someth2say** [comment]
You can also use `-f` to specify the location of the config file:

```
--config-file file_name, -f file_name
    Specify the configuration filename. If no file is named,
    xmlformat uses the file named by the environment variable
    XMLFORMAT_CONF, if it exists, or ./xmlformat.conf, if it
    exists. Otherwise, xmlformat uses built-in formatting
    options.
```

Anyway, XDG spec is something I would love to explore, as it actually makes much more sense than using a dedicated env var. 
I would propose $XDG_CONFIG_HOME first, then $XDG_CONFIG_DIRS:

1. The file in the `-f` option, if set.
2. `./xmlformat.conf` (file in $cwd)
3. `$XDG_CONFIG_HOME/xmlformat.conf`
4. `xmlformat.conf` in each of `$XDG_CONFIG_DIRS`
5. Default built-in config.

I am reluctant to defaulting to `/etc/xmlformat.conf` as this folder may not even exist.

**Comment by tomschr** [comment]
Thanks for the quick reply! :slightly_smiling_face: 

> You can also use -f to specify the location of the config file:

That's true. I'm aware of it. :slightly_smiling_face: It's just another level of providing the config file. 

> I am reluctant to defaulting to `/etc/xmlformat.conf` as this folder may not even exist.

If you consider other platforms than Linux, then yes. :wink:
