### ISSUE TITLE
Adapt version output

### ISSUE THREAD

**Issue by tomschr** [someth2say/xmlformat#8]
# Situation

when using `xmlformat.pl --version` or `xmlformat.rb --version` it shows the version. However, it still prints `1.04 (xxx version)`.

# Suggested solution

I see two issues with the current approach:

* It's not the correct version. You just tagged 0.4 and released it in this GitHub repo. :wink: 
* It doesn't show that's a fork, based on the original version from Kitebird.

IMHO, it should show something like this:

```
$ xmlformat --version
xmlformat 0.4 (based on Kitebird xmlformat 1.04)
```

(or any other form which makes sense)

It's a tiny thing, however, can become quite important.

For example, the new option `wrap-type` is only known in the fork, not in the original implementation. That means, you can't have a single config file for both scripts. To automatically distinguish between both scripts, the version string is the only reliable way to do that.

**Comment by someth2say** [comment]
Completelly up to it!
I guess that for a first approach we can just set the version message directly in code, but later maintenance may need this to be moved to an outside file (such as a pom.xml or other).

I'm now head-s down to another change (that may drive to v2.0), but totally accept it!

**Comment by tomschr** [comment]
Thank you! :slightly_smiling_face: 

> I guess that for a first approach we can just set the version message directly in code, but later maintenance may need this to be moved to an outside file (such as a pom.xml or other).

In the Python world, there is the `bump2version` script. :wink: You basically define all the files in a config file which contain version strings. When you bump your version, the script will raise all the version strings in the defined files and creates a commit. Probably that is a bit too much for that one.

> I'm now head-s down to another change (that may drive to v2.0), but totally accept it!

Great! Is it okay to create a pull request with this change? I don't want to step on your changes. :wink:

**Comment by someth2say** [comment]
I opted for manually adapting the version number.
I added a script for building the container image, so I hope I don't forget to change the versioning :)
Anyway, I am creating an issue for setting up a GH action that does that for us.
The latest release is here: https://github.com/someth2say/xmlformat/releases/tag/1.9
